import Head from 'next/head'
import styles from './styles/layout.module.css'

type Props = {
    children: JSX.Element
}

const Layout = ({ children }: Props): JSX.Element => {
    return (
        <div>
            <Head>
                <title>Note Next app</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                {children}
            </main>
        </div>
    )
}

export default Layout